

CREATE TABLE Usuario (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  EDAD INT,
  PESO DECIMAL(10,2),
  TALLA DECIMAL(5,2),
  MEMBRESIA VARCHAR(50),
  FechaRegistro DATETIME DEFAULT GETDATE()
);
